name: Linux RDP (Playit.gg Fast Tunnel)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
    - name: Install Desktop Environment & XRDP
      run: |
        sudo apt update
        sudo apt install -y xfce4 xfce4-goodies xrdp
        sudo adduser runner xrdp
        echo "xfce4-session" > ~/.xsession
        sudo service xrdp restart

    - name: Set RDP Password
      run: |
        echo "runner:Pass123456!@#" | sudo chpasswd

    - name: Setup & Run Playit.gg
      run: |
        curl -SsL https://playit-cloud.github.io/get-playit/playit-pkgs.gpg | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/playit.gpg
        echo "deb [signed-by=/etc/apt/trusted.gpg.d/playit.gpg] https://playit-cloud.github.io/get-playit/ /" | sudo tee /etc/apt/sources.list.d/playit.list
        sudo apt update
        sudo apt install playit -y
        
        echo "=========================================="
        echo "🚀 PLAYIT TUNNEL STARTING..."
        echo "=========================================="
        playit --secret "" || true
